# Generated by Django 2.0 on 2019-10-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='passw',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='uname',
        ),
    ]
